# -*- coding: utf-8 -*-
"""ai_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QokE4izpTuXF8e7X18hGX3I5z-MrXZJT
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("grafstor/simple-dialogs-for-chatbot")

print("Path to dataset files:", 'https://www.kaggle.com/datasets/niraliivaghani/chatbot-dataset')

import kagglehub
import os
import random
import string
import re
from collections import defaultdict

# Step 1: Load the Dataset
def load_dataset(path):
    try:
        with open(path, "r", encoding="utf-8") as file:
            data = file.read()
        return data
    except FileNotFoundError:
        print("Dataset not found. Please check the file path.")
        return ""

# Step 2: Preprocess the Text
def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r"\d+", "", text)  # Remove numbers
    text = re.sub(r"\s+", " ", text)  # Remove extra spaces
    text = text.translate(str.maketrans("", "", string.punctuation))  # Remove punctuation
    return text

# Step 3: Build the Markov Chain
def build_markov_chain(words):
    markov_chain = defaultdict(list)
    for current_word, next_word in zip(words, words[1:]):
        markov_chain[current_word].append(next_word)
    return markov_chain

# Step 4: Generate a Sentence
def generate_sentence(chain, start_word, length=10):
    word = start_word
    sentence = [word]

    for _ in range(length - 1):
        if word in chain:
            word = random.choice(chain[word])  # Randomly select the next word
            sentence.append(word)
        else:
            break

    return " ".join(sentence)

# Step 5: Implement a Simple Chatbot
def chatbot(chain, words):
    print("Chatbot: Hi! I'm here to chat with you. Type 'quit' to exit.")
    while True:
        user_input = input("You: ").lower()
        if user_input == "quit":
            print("Chatbot: Bye! Have a great day.")
            break

        # Generate a response
        start_word = user_input.split()[-1] if user_input.split() else random.choice(words)
        response = generate_sentence(chain, start_word)
        print(f"Chatbot: {response}")

# Main Program
if __name__ == "__main__":
    # Download the dataset
    dataset_dir = kagglehub.dataset_download("grafstor/simple-dialogs-for-chatbot")

    # Assume the dataset file is named "dialogs.txt" - adjust if necessary
    dataset_path = os.path.join(dataset_dir, "dialogs.txt")

    raw_data = load_dataset(dataset_path)

    if raw_data:
        # Preprocess the dataset
        cleaned_data = preprocess_text(raw_data)
        words = cleaned_data.split()

        # Build the Markov Chain
        markov_chain = build_markov_chain(words)

        # Run the chatbot
        chatbot(markov_chain, words)